### ISSUE TITLE
Conversion is not so good

### ISSUE THREAD

**Issue by 743v45** [jonathansamines/format-link-header#3]
It is the link that github returned.
`curl -I "https://api.github.com/search/code?q=addClass+user:mozilla&page=2"`

`
<https://api.github.com/search/code?q=addClass+user%3Amozilla&page=3>; rel="next", <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=34>; rel="last", <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=1>; rel="first", <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=1>; rel="prev"
`

```
[ { page: 3,
    per_page: 5,
    rel: 'next',
    url: '/api/messages?per_page=5&page=3' },
  { page: 1,
    per_page: 5,
    rel: 'prev',
    url: '/api/messages?per_page=5&page=1' },
  { page: 1,
    per_page: 5,
    rel: 'first',
    url: '/api/messages?per_page=5&page=1' },
  { page: 3,
    per_page: 5,
    rel: 'last',
    url: '/api/messages?per_page=5&page=3' } ]
```

got this.

`</api/messages?per_page=5&page=3>; rel="next last", </api/messages?per_page=5&page=1>; rel="prev first"`

**Comment by jonathansamines** [comment]
Hi @zyvas what is happening is that is grouping the links with the same URL, I am not really aware whether or not that an standard and expected behaviour or at least is a valid equivalent to the original input. Do you have any knowledge on that?

**Comment by jonathansamines** [comment]
Closing due inactivity. Please feel free to open with additional details if still relevant.
